// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package api

// Problem defines model for Problem.
type Problem struct {
	Statement string `json:"statement"`
}
