// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package models

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Problem defines model for Problem.
type Problem struct {
	Statement string `json:"statement"`
}

// ProblemId defines model for ProblemId.
type ProblemId = openapi_types.UUID
