// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package models

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Problem defines model for Problem.
type Problem struct {
	Statement string `json:"statement"`
}

// ProblemId defines model for ProblemId.
type ProblemId = openapi_types.UUID
