// Code generated by "stringer -type=TestingSystemType"; DO NOT EDIT.

package problem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Timus-0]
}

const _TestingSystemType_name = "Timus"

var _TestingSystemType_index = [...]uint8{0, 5}

func (i TestingSystemType) String() string {
	if i < 0 || i >= TestingSystemType(len(_TestingSystemType_index)-1) {
		return "TestingSystemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestingSystemType_name[_TestingSystemType_index[i]:_TestingSystemType_index[i+1]]
}
